play_list: # 视频播放列表
    - https://www.bilibili.com/video/BV1WH4y127qe # 动画
    - https://www.bilibili.com/video/BV1ga4y1U7FP # 动画 59s
    - https://www.bilibili.com/video/BV1Tb4y1u7Z8 # 舞蹈
    - https://www.bilibili.com/video/BV1Sc41167Ru # 娱乐
    - https://www.bilibili.com/video/BV1dv411c7Tu
    - https://www.bilibili.com/video/BV1Eu4y1P78t
    - https://www.bilibili.com/video/BV1qC4y117bN
    - https://www.bilibili.com/video/BV1F94y1H7z4
    - https://www.bilibili.com/video/BV1EG411D7NS
    - https://www.bilibili.com/video/BV1gC4y1S7Rd
    - https://www.bilibili.com/video/BV1ib4y1u7cc
    - https://www.bilibili.com/video/BV1Ka4y1U7HV
    - https://www.bilibili.com/video/BV1JG411D7VF
    - https://www.bilibili.com/video/BV1iG411D7jT
    - https://www.bilibili.com/video/BV1Uw411P7m4

net_interface: WLAN # 抓包网络接口

play_resolutions: # 每次运行插件会用下列配置的的每种分辨率分布采集一轮上面的全部视频
    - auto # B站自动调节分辨率
    - 360p # 取消注释即可采集一轮对应分辨率的视频
    - 480p
    - 720p
    - 1080p

# 是否全屏播放
fullscreen_play: false

ssh_host: 192.168.31.1
ssh_port: 22
ssh_username: root
ssh_password: 4bcc8d55

device_ip: 192.168.31.146 # 设备IP

router_lan_interface: br-lan # 内网网卡上做限速，限制的是下载速度


net_cond_list: # rate 单位Kbit
    # - 
    #     type: random_bandwidth # 跑三遍，900个样本
    #     max_rate: 6000 # 5000Kbps
    #     min_rate: 600 # 100Kbps
    #     change_interval: 3 # 5s
    #     need_unpack: False
    # -
    #     need_unpack: true # 由程序将该配置解包成多个配置，rates中每个rate转为一个配置
    #     type: constant_bandwidth # 3900个样本
    #     rates: [  
    #             # 2000, 3000]
    #             # 3000, 4000, 5000,]
    #             #   8000, 10000, 
    #             20000, 50000, 100000]
    -
        need_unpack: False
        type: trace_bandwidth # 维持在一个速率（Kbps）持续一段时间（s）
        trace: [[100000, 10], [10000, 10], [100000, 1]]
        id: 1

