play_list: # 视频播放列表
    - https://www.bilibili.com/video/BV1WH4y127qe # 动画
    - https://www.bilibili.com/video/BV1ga4y1U7FP # 动画 59s
    - https://www.bilibili.com/video/BV1Tb4y1u7Z8 # 舞蹈
    - https://www.bilibili.com/video/BV1Sc41167Ru # 娱乐
    - https://www.bilibili.com/video/BV1dv411c7Tu
    - https://www.bilibili.com/video/BV1Eu4y1P78t
    - https://www.bilibili.com/video/BV1qC4y117bN
    - https://www.bilibili.com/video/BV1F94y1H7z4
    - https://www.bilibili.com/video/BV1EG411D7NS
    - https://www.bilibili.com/video/BV1gC4y1S7Rd
    - https://www.bilibili.com/video/BV1ib4y1u7cc
    - https://www.bilibili.com/video/BV1Ka4y1U7HV
    - https://www.bilibili.com/video/BV1JG411D7VF
    - https://www.bilibili.com/video/BV1iG411D7jT
    - https://www.bilibili.com/video/BV1Uw411P7m4

net_interface: 以太网 # 抓包网络接口

play_resolutions: # 每次运行插件会用下列配置的的每种分辨率分布采集一轮上面的全部视频
    - 1080p
    # - 720p
    # - 480p
    # - 360p # 取消注释即可采集一轮对应分辨率的视频
    # - auto # B站自动调节分辨率

# 是否全屏播放
fullscreen_play: false

ssh_host: 192.168.31.244
ssh_port: 22
ssh_username: root
ssh_password: password

# net_cond_list:


