play_list: # 视频播放列表
    - https://www.bilibili.com/video/BV1WH4y127qe # 动画
    - https://www.bilibili.com/video/BV1ga4y1U7FP # 动画 59s
    - https://www.bilibili.com/video/BV1Tb4y1u7Z8 # 舞蹈
    - https://www.bilibili.com/video/BV1Sc41167Ru # 娱乐
    - https://www.bilibili.com/video/BV1dv411c7Tu
    - https://www.bilibili.com/video/BV1Eu4y1P78t
    - https://www.bilibili.com/video/BV1qC4y117bN
    - https://www.bilibili.com/video/BV1F94y1H7z4
    - https://www.bilibili.com/video/BV1EG411D7NS
    - https://www.bilibili.com/video/BV1gC4y1S7Rd
    - https://www.bilibili.com/video/BV1ib4y1u7cc
    - https://www.bilibili.com/video/BV1Ka4y1U7HV
    - https://www.bilibili.com/video/BV1JG411D7VF
    - https://www.bilibili.com/video/BV1iG411D7jT
    - https://www.bilibili.com/video/BV1Uw411P7m4

net_interface: 以太网 # 抓包网络接口

play_resolutions: # 每次运行插件会用下列配置的的每种分辨率分布采集一轮上面的全部视频
    - 1080p
    # - 720p
    # - 480p
    # - 360p # 取消注释即可采集一轮对应分辨率的视频
    # - auto # B站自动调节分辨率

# 是否全屏播放
fullscreen_play: false

ssh_host: 192.168.31.1
ssh_port: 22
ssh_username: root
ssh_password: 4bcc8d55

device_ip: 192.168.31.56 # 设备IP

router_lan_interface: br-lan # 内网网卡上做限速，限制的是下载速度

net_cond_list: # rate 单位Kbit
    - 
        rate: 1000 # 1Mbps
        duration: 10 # 60s
        start_time: 0 # 0s
    - 
        rate: 1000 # 1Mbps
        duration: 10 # 60s
        start_time: 10 # 10s
    -
        rate: 1000 # 1Mbps
        duration: 10 # 60s
        start_time: 20 # 20s
    -
        rate: 1000 # 1Mbps
        duration: 10 # 60s
        start_time: 30 # 30s
    -
        rate: 1000 # 1Mbps
        duration: 10 # 60s
        start_time: 40 # 40s
    -
        rate: 1000 # 1Mbps
        duration: 10 # 60s
        start_time: 50 # 50s
    # - rate: 3000 # 3Mbps
    # - rate: 4000 # 4Mbps
    # - rate: 5000 # 5Mbps
    # - rate: 6000 # 6Mbps
    # - rate: 7000 # 7Mbps
    # - rate: 8000 # 8Mbps
    # - rate: 9000 # 9Mbps
    # - rate: 10000 # 10Mbps


