# yaml 配置实例
version: "2"
services:
  bili_autoplay:
    image: markadams/chromium-xvfb-py3
    volumes:
    - $PWD:/home
    container_name: bili_autoplay
    working_dir: /home
    dns:
      - 114.114.114.114
      - 8.8.8.8
    command:
       /bin/bash -c " pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ && python3 main.py"

